name: Sync from upstream

on:
  workflow_dispatch:  # 수동 실행 버튼 추가

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork (origin)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # 전체 히스토리 가져오기 (merge 위해 필요)

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/FarmRanding/frontend.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/5-feature-fixbug → origin/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit

      - name: Push to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/kanguk01/farmrandingFE.git main
